language: csharp
mono: none
dotnet: 3.0
os: linux
dist: xenial
sudo: false
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - ./build.sh
  
deploy:
  - provider: script
    script: ./deploy-tag.sh
    on:
      tags: true