trigger:
  branches:
    include:
      - '*'
      - refs/tags/*

jobs:

- job: Build_Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      useGlobalJson: true
  - bash: |
      ./build.sh
    displayName: 'Build'
    env:
      COVERALLS_REPO_TOKEN: '$(COVERALLS_REPO_TOKEN)'
  - bash: |
      ./build-sample.sh
    displayName: 'Build Sample'
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/cobertura.xml'

- job: Build_Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      useGlobalJson: true
  - bash: |
      ./build.sh
    displayName: 'Build'

- job: Push_Package
  dependsOn:
    - Build_Windows
    - Build_Linux
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      useGlobalJson: true
  - bash: |
      export Version=${TagName:1}
      dotnet pack -c Release -o nupkg
      dotnet nuget push "nupkg/*.nupkg" -k $NUGET_KEY -s https://api.nuget.org/v3/index.json --skip-duplicate
    env:
      TagName: '$(Build.SourceBranchName)'
      NUGET_KEY: '$(NUGET_KEY)'
    displayName: 'Release'
    
